### ISSUE TITLE
Array index out-of-bounds (index 6006, limit 6000)

### ISSUE THREAD

**Issue by gost442** [z1ntex/CSGO_WeaponStickers#12]
Exception reported: Array index out-of-bounds (index 6006, limit 6000)
L 10/23/2022 - 17:13:29: [SM] Blaming: csgo_weaponstickers.smx
L 10/23/2022 - 17:13:29: [SM] Call stack trace:

**Comment by crashzk** [comment]
Just download PR: https://github.com/z1ntex/CSGO_WeaponStickers/pull/13

Author just forgot to compile.

[CSGO_WeaponStickers-master.zip](https://github.com/z1ntex/CSGO_WeaponStickers/files/9847406/CSGO_WeaponStickers-master.zip)

**Comment by z1ntex** [comment]
@crashzk Make a post on the allied forum with a link to the finished release https://github.com/z1ntex/CSGO_WeaponStickers/releases/tag/v1.3.5
