### ISSUE TITLE
stickers not saving

### ISSUE THREAD

**Issue by Juller12** [z1ntex/CSGO_WeaponStickers#22]
Hi, i get this error when i reconnect to my server 
![image](https://user-images.githubusercontent.com/123899537/225070818-ac57f117-2f89-4858-b2f4-114397b53784.png)

**Comment by crashzk** [comment]
@Juller12 using SQLIte?

@z1ntex many users have been complaining about SQLite support, whenever the map changes, the stickers are removed.

**Comment by z1ntex** [comment]
Fixed
