### ISSUE TITLE
Update Stickers eItems

### ISSUE THREAD

**Issue by crashzk** [z1ntex/CSGO_WeaponStickers#24]
@z1ntex I would like to know if you could say, or send the script that you use to update the list of stickers, the `items_` list of eItems in this case.

**Comment by mrc4tt** [comment]
I would also like to know, now that new stickers have arrived today. ;-)

**Comment by z1ntex** [comment]
@crashzk You can correct the sticker curves in categories or add new ones, as well as add agent patches as stickers by changing the configuration manually. I could try to do it, but I don't have time for it at all.
