### ISSUE TITLE
VALVe Update 21.oct

### ISSUE THREAD

**Issue by mrc4tt** [z1ntex/CSGO_WeaponStickers#9]
L 10/22/2022 - 11:52:19: [SM] Exception reported: Array index out-of-bounds (index 6006, limit 6000)
L 10/22/2022 - 11:52:19: [SM] Blaming: csgo_weaponstickers.smx
L 10/22/2022 - 11:52:19: [SM] Call stack trace:
L 10/22/2022 - 11:52:19: [SM]   [1] Line 162, C:\Users\artem\OneDrive\������� ����\scripting\csgo_weaponstickers.sp::Frame_ItemsSync

SourceMod version: **1.11.0.6913**

**Comment by crashzk** [comment]
Test: https://github.com/z1ntex/CSGO_WeaponStickers/pull/11

[csgo_weaponstickers.zip](https://github.com/z1ntex/CSGO_WeaponStickers/files/9844654/csgo_weaponstickers.zip)

**Comment by mrc4tt** [comment]
Thanks :+1:
